package com.bhawna.milksupplyproject.model;

import com.fasterxml.jackson.annotation.JsonProperty;

public class User {

	@JsonProperty
	private long id;

	@JsonProperty
	private String firstName;

	@JsonProperty
	private String lastName;

	@JsonProperty    
	private String phone;

	@JsonProperty
	private String email;

	@JsonProperty
	private String password;

	/**
	 * A no-argument constructor.
	 */
	public User() {

		super();
	}
	/**
	 * A constructor to create employees. Id is not passed, cause it's
	 * auto-generated by RDBMS.
	 *
	 */
	public User(String firstName, String lastName, String phone, String e_mail, String password) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.phone = phone;
		this.password = password;
	}
	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	public String getLastName() {
		return lastName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	public String getPhone() {
		return phone;
	}
	public void setPhone(String phone) {
		this.phone = phone;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	@Override
	public String toString() {
		return "User [id=" + id + ", firstName=" + firstName + ", lastName=" + lastName + ", phone=" + phone
				+ ", email=" + email + ", password=" + password + "]";
	}

}
